# Generated by Django 4.2 on 2023-06-14 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_firstname_alter_member_joined_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='joined_date',
            field=models.DateTimeField(null=True),
        ),
    ]
