# Generated by Django 4.2 on 2023-06-14 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
        ('members', '0004_alter_member_joined_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plans.plan'),
        ),
    ]
